### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by moh1122** [zhuoweiz/EasyConvert#1]
Nice project.
how to run it without .xcodeproj

**Comment by zhuoweiz** [comment]
Thanks for the notice. I will push an update later today.

**Comment by moh1122** [comment]
thank you @zhuoweiz for your quick reply

**Comment by zhuoweiz** [comment]
I uploaded the .xcodeproj file. Be aware that this repo has been out of maintenance for a while and it was mainly used as a reference for a hackathon project demo. Nonetheless, it runs on my computer well so should be fine.
